#!/bin/bash
#SBATCH -A k1254
#SBATCH -J extj_YEAR_EDITMON_EDIT
#SBATCH -N 1
#SBATCH -t 300
##SBATCH --partition=debug
#SBATCH --mem=MaxMemPerNode
#SBATCH -o /scratch/karumulb/Hari_data/logs/out_ext_YEAR_EDITMON_EDIT
#SBATCH -e /scratch/karumulb/Hari_data/logs/err_ext_YEAR_EDITMON_EDIT

module unload PrgEnv-cray  PrgEnv-gnu  PrgEnv-intel
#module load PrgEnv-cray
#module load wgrib2/3.0.0    cray-netcdf

#module swap PrgEnv-cray  PrgEnv-intel
#module load cdo/1.9.10 

module load PrgEnv-gnu
module load wgrib2
module load cdo
set -x 

date

export SRC=/project/k1254/rama/Hari_prasad/Scripts_work/Utils     ## where wgrib2 located 
export DATA=/project/k1254/hari/GRIB2DATA/GRIB2DATA   ## INPUT DATA PATH 
#export SRC=/scratch/desamss/ds.test/Jeff        ## SOURCE DIR (where this file exists)
export ODIR=/scratch/karumulb/Hari_data/wrkdir/Output             ## OUTPUT DIR 
export WRKDIR=/scratch/karumulb/Hari_data/wrkdir/sfc/    # WORKDIR 

year=YEAR_EDIT
mon=MON_EDIT

export WRK=$WRKDIR/${year}.${mon}

rm -rf $WRK 
mkdir -p $WRK $WRK/outs ; cd $WRK
export OUTDIR=$ODIR
[ ! -d $OUTDIR ] && mkdir -p $OUTDIR

cp -f  $SRC/sfc.table     .    ## Converts Input Variable to Output Variable names 
cp -f  $SRC/wgrib2       .

for dom in 2 ; do

ln -sf ${DATA}/DOM${dom}/${year}/${year}${mon}??.grb2     .


for file in ${year}${mon}??.grb2 ; do
  rm -f tmp.grb   tmp?.nc 
  day=`echo $file | cut -c7-8`
#  ./wgrib2 $file -match ":((TCDC):*):" -append  -GRIB tmp.grb
#  ./wgrib2 $file -match ":(LCDC:low cloud layer):|:(MCDC:middle cloud layer):|:(HCDC:high cloud layer):" -append  -GRIB tmp.grb
#  ./wgrib2 $file -match ":(([UV]GRD):10 m above ground):" -append  -GRIB tmp.grb
#  ./wgrib2 $file -match ":(([UV]GRD):10 m above ground):|:((SPFH|TMP):2 m above ground):|:PRMSL:|:PRES:|:POT:|:([UV]GRD):*:|:POT:*:|:HGT:*:" -append  -GRIB tmp.grb
#  ./wgrib2 $file -match ":(([UV]GRD):10 m above ground):|:((SPFH|TMP|RH):2 m above ground):|:PRMSL:|:PRES:|:POT:|:([UV]GRD):*:|:POT:*:|:HGT:*:" -append  -GRIB tmp.grb
#  ./wgrib2 $file -match ":([UV]GRD):*mb:" -append  -GRIB tmp.grb
#  ./wgrib2 $file -match ":PRMSL:|:PRES:|:([UV]GRD):*:|:POT:*:" -append  -GRIB tmp.grb
#  ./wgrib2 $file -match ":(([UV]GRD):10 m above ground):|:((RH|TMP):2 m above ground):|:PRMSL:" -append  -GRIB tmp.grb
  ./wgrib2 $file -match ":(([UV]GRD):10 m above ground):|:((RH|TMP):2 m above ground):" -append  -GRIB tmp.grb
#  ./wgrib2 $file -match ":(([UV]GRD):10 m above ground):|:PRMSL:" -append  -GRIB tmp.grb
#  ./wgrib2 $file -match ":(TMP:2 m above ground):" -append  -GRIB tmp.grb
#  ./wgrib2 $file -match ":(APCP:surface):" -append  -GRIB tmp.grb
#./wgrib2 $file -match ":((ALBDO|VIS):surface):|:(VIS:cloud top):" -append  -GRIB tmp.grb
  
  wgrib2  tmp.grb -nc_table sfc.table -netcdf  tmp1.nc
 # 35.3E-36.4E; 26.3N-27.5N 
# cdo -P 8 sellonlatbox,38,39.5,22,23  tmp1.nc   tmp2.nc 
  cdo -P 8 -remapnn,lon=36.593668_lat=28.424996  tmp1.nc   tmp2.nc 
#  cdo -P 8 sellonlatbox,32.9,36.6,26.4,29.1  tmp1.nc   tmp2.nc 
  cdo -P 8 seltimestep,13/36  tmp2.nc   tmp3.nc 
  mv  tmp3.nc    ./outs/uvpr_${year}${mon}${day}.nc 
  rm -f tmp?.nc  tmp.grb
  unlink $file
done   #file 

  cd ./outs
  export SKIP_SAME_TIME=1
  cdo -P 8 mergetime uvpr_${year}${mon}??.nc uvpr_${year}${mon}.nc   

  mv uvpr_${year}${mon}.nc  $OUTDIR/

done # dom
###

date
set +x 

exit

